# Generator hyperparameters
Generator:
  model_name: "facebook/bart-base"
  tokenizer_name: "facebook/bart-base"
  max_length: 1024
  temperature: 0.8
  top_k: 50
  top_p: 0.9
  repetition_penalty: 1.0
  batch_size: 8
  num_epochs: 3
  learning_rate: 0.00005
  adam_epsilon: 1e-8
  weight_decay: 0.01

# Discriminator hyperparameters
Discriminator:
  model_name: "distilbert-base-uncased"
  tokenizer_name: "distilbert-base-uncased"
  max_seq_length: 256
  batch_size: 16
  num_epochs: 5
  learning_rate: 0.00002
  dropout_prob: 0.1
  hidden_size: 768

# Scorer hyperparameters
Scorer:
  max_seq_length: 384
  batch_size: 32

# Training parameters
Training:
  batch_size: 8
  max_epochs: 10
  learning_rate: 0.00002

# Data paths
train_data_path: data/squad_v2/processed_data.json
dev_data_path: data/squad_v2/dev-v2.0.json

# Output paths
generator_checkpoint_path: models/generator/checkpoint.pth.tar
discriminator_checkpoint_path: models/discriminator/checkpoint.pth.tar
scorer_checkpoint_path: models/scorer/checkpoint.pth.tar
generated_answers_path: data/generated_answers.json
